openapi: 3.0.0
info:
  version: 0.0.1
  title: sktime forecast
servers:
  - url: 'http://localhost:3000'
paths:
  /forecast:
    post:
      description:
        Sending time series which needs to be forecasted
      operationId: naive_forecast
      requestBody:
        required: true
        content: 
            ts_forecast_data/json
                schema:
                    properties: 
                       time_series:
                         type: array
                         items:
                           type: number 

  /user:
    get:
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: listUser
      tags:
        - user
      parameters:
        - name: id
          in: query
          description: ID of the user
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string